- title:      App Security
  description:  We have extensive experience in utilizing encryption techniques, using high-end algorithms to secure your applications throughout the entire stack.		
  fa-icon:      fa-object-group
  link:         

- title:      Full-Stack Development
  description:  We are experts in using the Angular, TypeScript, React frameworks and the Microsoft stack; having high-class, exceptional expertise in C#, Microsoft Azure and the .NET Core framework.			
  fa-icon:      fa-code
  link:         

- title:      App Testing
  description:  We test your applications using different testing methodologies and tools; including end-to-end, unit and system integration testing.			
  fa-icon:      fa-paper-plane-o
  link:         
