- title:      App Security
  description:  Development and utilization of encryption techniques, using high-end algorithms to secure your applications in the entire stack.		
  fa-icon:      fa-object-group
  link:         

- title:      Full-Stack Development
  description:  Specialization in Angular, TypeScript, React and the Microsoft stack; including high-class exceptional expertise in C#, Microsoft Azure and the .NET Core framework.			
  fa-icon:      fa-code
  link:         

- title:      Testing
  description:  Utilization of testing methodologies and tools, including end-to-end, unit and system integration testing.			
  fa-icon:      fa-paper-plane-o
  link:         
